version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    networks:
      - app_network

  proxy:
    image: nginx:alpine
    container_name: app_proxy
    ports:
      - "8080:80"
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app_network:
    driver: bridge
